#!/usr/bin/env python3
"""
maintain_reference_database.py — Keep a reference database index in sync.

This script rebuilds workspace/reference_database/index.json from the Markdown
summaries that actually live in workspace/reference_database/summaries. When a
citation pool is supplied, it also reports which pool references are missing or
corrupt and should be regenerated by build_reference_database.py.

Usage:
    python maintain_reference_database.py --workspace workspace --fix
    python maintain_reference_database.py --pool workspace/citation_pool.json --fix
"""
import argparse
import json
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass
class SummaryHealth:
    key: str
    path: Path
    ok: bool
    reason: str


@dataclass
class MaintenanceResult:
    index_path: Path
    rows: list[dict]
    changed: bool
    problems: list[str]
    regenerate_keys: set[str]


def load_pool(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def pool_papers(pool_data: object) -> list[dict]:
    if isinstance(pool_data, dict):
        papers = pool_data.get("papers", [])
        return papers if isinstance(papers, list) else []
    return pool_data if isinstance(pool_data, list) else []


def parse_frontmatter_text(text: str) -> dict:
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    fields: dict[str, str] = {}
    for line in text[3:end].splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        fields[key.strip()] = value.strip().strip('"')
    return fields


def parse_frontmatter(path: Path) -> dict:
    if not path.exists():
        return {}
    return parse_frontmatter_text(path.read_text(encoding="utf-8", errors="replace"))


def first_heading(text: str) -> str:
    match = re.search(r"^#\s+(.+?)\s*$", text, flags=re.M)
    return match.group(1).strip() if match else ""


def extract_technical_summary(md_path: Path) -> str:
    if not md_path.exists():
        return ""
    content = md_path.read_text(encoding="utf-8", errors="replace")
    match = re.search(r"## Technical Summary\s*\n+(.*?)\n+## Problem", content, flags=re.S)
    if match:
        return match.group(1).strip()
    return ""


def relative_to_workspace(path: Path, workspace: Path) -> str:
    try:
        return os.path.relpath(path, workspace)
    except ValueError:
        return str(path)


def pdf_status_for_summary(workspace: Path, key: str, fields: dict) -> str:
    pdf_path = fields.get("pdf_path", "")
    candidates: list[Path] = []
    if pdf_path:
        candidate = Path(pdf_path)
        candidates.append(candidate if candidate.is_absolute() else workspace / candidate)
    candidates.append(workspace / "reference_database" / "papers" / f"{key}.pdf")
    return "existing" if any(path.exists() for path in candidates) else "missing"


def summary_status(fields: dict) -> str:
    return fields.get("summary_status", "").strip()


def check_summary(summary_path: Path, expected_key: str) -> SummaryHealth:
    if not summary_path.exists():
        return SummaryHealth(expected_key, summary_path, False, "missing summary")

    text = summary_path.read_text(encoding="utf-8", errors="replace")
    fields = parse_frontmatter_text(text)
    if not fields:
        return SummaryHealth(expected_key, summary_path, False, "missing frontmatter")
    if fields.get("bibtex_key") != expected_key:
        return SummaryHealth(expected_key, summary_path, False, "frontmatter bibtex_key mismatch")
    if summary_status(fields) != "complete":
        return SummaryHealth(expected_key, summary_path, False, f"summary_status={summary_status(fields)!r}")
    if not extract_technical_summary(summary_path):
        return SummaryHealth(expected_key, summary_path, False, "missing technical summary")

    return SummaryHealth(expected_key, summary_path, True, "")


def row_from_summary(summary_path: Path, workspace: Path) -> tuple[dict, str]:
    text = summary_path.read_text(encoding="utf-8", errors="replace")
    fields = parse_frontmatter_text(text)
    key = fields.get("bibtex_key") or summary_path.stem
    status = summary_status(fields) or "unknown"
    row = {
        "bibtex_key": key,
        "title": fields.get("title") or first_heading(text) or key,
        "location": relative_to_workspace(summary_path, workspace),
        "year": str(fields.get("year", "")),
        "summary": extract_technical_summary(summary_path),
        "status": f"{status};{pdf_status_for_summary(workspace, key, fields)}",
    }
    problem = "" if fields.get("bibtex_key") else f"{summary_path}: missing frontmatter bibtex_key"
    return row, problem


def index_rows_from_summaries(workspace: Path) -> tuple[list[dict], list[str]]:
    summary_dir = workspace / "reference_database" / "summaries"
    summary_dir.mkdir(parents=True, exist_ok=True)

    rows: list[dict] = []
    problems: list[str] = []
    seen_keys: set[str] = set()
    for summary_path in sorted(summary_dir.glob("*.md")):
        row, problem = row_from_summary(summary_path, workspace)
        key = row.get("bibtex_key", "")
        if key in seen_keys:
            problems.append(f"duplicate summary bibtex_key: {key}")
            continue
        seen_keys.add(key)
        rows.append(row)
        if problem:
            problems.append(problem)

    rows.sort(key=lambda item: (item.get("title", ""), item.get("bibtex_key", "")))
    return rows, problems


def read_index(index_path: Path) -> list[dict]:
    if not index_path.exists():
        return []
    try:
        data = json.loads(index_path.read_text(encoding="utf-8"))
    except Exception:
        return []
    papers = data.get("papers", [])
    return papers if isinstance(papers, list) else []


def write_index(index_path: Path, rows: list[dict]) -> None:
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(json.dumps({"papers": rows}, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def maintain_reference_database(
    workspace: Path,
    papers: list[dict] | None = None,
    fix: bool = False,
) -> MaintenanceResult:
    workspace = workspace.resolve()
    index_path = workspace / "reference_database" / "index.json"
    rows, problems = index_rows_from_summaries(workspace)
    existing_rows = read_index(index_path)
    changed = existing_rows != rows

    if changed and fix:
        write_index(index_path, rows)
    elif changed:
        problems.append(f"index out of sync: {index_path}")

    regenerate_keys: set[str] = set()
    if papers is not None:
        summary_dir = workspace / "reference_database" / "summaries"
        seen_keys: set[str] = set()
        for paper in papers:
            key = paper.get("bibtex_key")
            if not key:
                problems.append(f"pool paper missing bibtex_key: {paper.get('title', 'unknown title')}")
                continue
            if key in seen_keys:
                problems.append(f"duplicate bibtex_key in pool: {key}")
            seen_keys.add(key)

            health = check_summary(summary_dir / f"{key}.md", key)
            if not health.ok:
                regenerate_keys.add(key)
                problems.append(f"{health.path}: {health.reason}")

        summary_keys = {row.get("bibtex_key", "") for row in rows if row.get("bibtex_key")}
        for key in sorted(summary_keys - seen_keys):
            problems.append(f"{summary_dir / (key + '.md')}: orphan summary with no pool entry")

    return MaintenanceResult(
        index_path=index_path,
        rows=rows,
        changed=changed,
        problems=problems,
        regenerate_keys=regenerate_keys,
    )


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    group = p.add_mutually_exclusive_group(required=True)
    group.add_argument("--workspace", help="Workspace containing reference_database/")
    group.add_argument("--pool", help="citation_pool.json; workspace is inferred from this file's parent")
    p.add_argument("--fix", action="store_true", help="Rewrite index.json when it is out of sync")
    args = p.parse_args()

    workspace = Path(args.pool).resolve().parent if args.pool else Path(args.workspace).resolve()
    papers = pool_papers(load_pool(Path(args.pool))) if args.pool else None
    result = maintain_reference_database(workspace=workspace, papers=papers, fix=args.fix)

    if result.changed and args.fix:
        print(f"OK: wrote {len(result.rows)} rows -> {result.index_path}")
    elif not result.changed:
        print(f"OK: reference index synchronized ({len(result.rows)} summaries)")

    if result.regenerate_keys:
        print(f"NEEDS_REGEN: {', '.join(sorted(result.regenerate_keys))}")

    if result.problems:
        for problem in result.problems:
            print(f"WARN: {problem}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
